services:
  agromapping-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:

      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - agromapping_network

  db:
    image: postgres:13-alpine
    environment:
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agromapping_network

volumes:
  pg_data:

networks:
  agromapping_network:
    driver: bridge