# docker-compose.yml

version: '3.8'

services:
  agromapping-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      # Mapeando as variáveis do seu .env para as que o Spring Boot usa
      SPRING_DATASOURCE_URL: ${URL_BANCO}
      SPRING_DATASOURCE_USERNAME: ${USUARIO}
      SPRING_DATASOURCE_PASSWORD: ${SENHA}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - agromapping_network

  db:
    image: postgres:13-alpine
    environment:
      # IMPORTANTE: As credenciais do banco devem ser as mesmas que a aplicação usa
      POSTGRES_DB: AgroMapping # O nome do banco já está na sua URL_BANCO
      POSTGRES_USER: ${USUARIO} # Usando a variável USUARIO para criar o usuário no banco
      POSTGRES_PASSWORD: ${SENHA} # Usando a variável SENHA para a senha do banco
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      # O healthcheck também precisa usar as credenciais corretas
      test: ["CMD-SHELL", "pg_isready -U ${USUARIO} -d AgroMapping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agromapping_network

volumes:
  pg_data:

networks:
  agromapping_network:
    driver: bridge
